server:
  port: 8085

spring:
  application:
    name: service-product-consumer-fegin

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  httpclient:
    enabled: true

